//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrict_IS._database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryWeapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilitaryWeapon()
        {
            this.MilitaryWeaponsInMilitaryBase = new HashSet<MilitaryWeaponsInMilitaryBase>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryOfMilitaryWeaponId { get; set; }
        public string Name { get; set; }
    
        public virtual CategoryOfMilitaryWeapon CategoryOfMilitaryWeapon { get; set; }
        public virtual KindOfMilitaryWeapon_ KindOfMilitaryWeapon_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryWeaponsInMilitaryBase> MilitaryWeaponsInMilitaryBase { get; set; }
    }
}
