//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrict_IS._database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilitaryDistrict()
        {
            this.PartsOfMilitaryDistrict = new HashSet<PartsOfMilitaryDistrict>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CommanderId { get; set; }
    
        public virtual Commander Commander { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartsOfMilitaryDistrict> PartsOfMilitaryDistrict { get; set; }
    }
}
