//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryDistrict_IS._database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialtyOfSoldier
    {
        public int Id { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<int> SoldierId { get; set; }
    
        public virtual Soldier Soldier { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
